// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_socark2;
lv_obj_t * ui_socvalueC;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Panel_messaggiC;  // Panel sfondo messaggi Screen2
lv_obj_t * ui_messaggiC;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3 - STATISTICHE VIAGGI
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_chart_trips;
lv_obj_t * ui_stats_panel;
lv_obj_t * ui_label_title;
lv_obj_t * ui_label_avg_consumption;
lv_obj_t * ui_label_avg_regen;
lv_obj_t * ui_label_total_trips;
lv_obj_t * ui_label_best_trip;
lv_obj_t * ui_label_back_hint;

// SCREEN: ui_Screen4 - VISUALIZZAZIONE JPG DA SD
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_Screen4_Image;
lv_obj_t * ui_Screen4_Label_Status;

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_socark_bg_inner;     // DEFINIZIONE MANCANTE
lv_obj_t * ui_automark_bg_inner;   // DEFINIZIONE MANCANTE

lv_obj_t * ui_socark_bg;      // Cerchio ombra SOC
lv_obj_t * ui_automark_bg;    // Cerchio ombra Autonomia
lv_obj_t * ui_ombraDXArancio;
lv_obj_t * ui_ombraDXRosso;
lv_obj_t * ui_ombraDX;
lv_obj_t * ui_ombraSX;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_gear;
lv_obj_t * ui_gearvalue;
lv_obj_t * ui_speedvalue;
lv_obj_t * ui_knh;
lv_obj_t * ui_odo;
lv_obj_t * ui_odovalue;
lv_obj_t * ui_socark;
lv_obj_t * ui_automark;
lv_obj_t * ui_socvalue;
lv_obj_t * ui_soc;
lv_obj_t * ui_automvalue;
lv_obj_t * ui_Label6;
lv_obj_t * ui_regenbar;
lv_obj_t * ui_regenbar_sep1;
lv_obj_t * ui_regenbar_sep2;
lv_obj_t * ui_powerbar;
lv_obj_t * ui_powerbar_sep1;
lv_obj_t * ui_powerbar_sep2;
lv_obj_t * ui_cerchioDX;
lv_obj_t * ui_cerchioSX;
lv_obj_t * ui_messaggi;
lv_obj_t * ui_regenvalue;
lv_obj_t * ui_powervalue;
lv_obj_t * ui_Battery;
lv_obj_t * ui_battemp;
lv_obj_t * ui_sport;
lv_obj_t * ui_Labelsport;
lv_obj_t * ui_normal;
lv_obj_t * ui_Labelnormal;
lv_obj_t * ui_ice;
lv_obj_t * ui_Labelice;
lv_obj_t * ui_reset;
lv_obj_t * ui_Labelreset;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);

    // FIX: Ripristinato caricamento di ui_Screen1 (era bloccato da schermo nero di debug)
    lv_disp_load_scr(ui_Screen1);
}
