// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_socark2;
extern lv_obj_t * ui_socvalueC;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel_messaggiC;  // Panel sfondo messaggi Screen2
extern lv_obj_t * ui_messaggiC;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3 - STATISTICHE VIAGGI
void ui_Screen3_screen_init(void);
void ui_Screen3_update_chart(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_chart_trips;
extern lv_obj_t * ui_stats_panel;
extern lv_obj_t * ui_label_title;
extern lv_obj_t * ui_label_avg_consumption;
extern lv_obj_t * ui_label_avg_regen;
extern lv_obj_t * ui_label_total_trips;
extern lv_obj_t * ui_label_best_trip;
extern lv_obj_t * ui_label_back_hint;

// SCREEN: ui_Screen4 - VISUALIZZAZIONE JPG DA SD
void ui_Screen4_screen_init(void);
void ui_Screen4_screen_deinit(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Screen4_Image;
extern lv_obj_t * ui_Screen4_Label_Status;

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);

// DICHIARAZIONI OGGETTI UI_SCREEN1 - CORRETTE E COMPLETE
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_gear;
extern lv_obj_t * ui_gearvalue;
extern lv_obj_t * ui_speedvalue;
extern lv_obj_t * ui_knh;
extern lv_obj_t * ui_odo;
extern lv_obj_t * ui_odovalue;

// === CERCHI E ARCHI SOC ===
extern lv_obj_t * ui_socark_bg;           // Cerchio di base SOC
extern lv_obj_t * ui_socark_bg_inner;     // Cerchio interno SOC - AGGIUNTO
extern lv_obj_t * ui_socark;              // Arco SOC

// === CERCHI E ARCHI AUTONOMIA ===
extern lv_obj_t * ui_automark_bg;         // Cerchio di base AUTONOMIA - AGGIUNTO
extern lv_obj_t * ui_automark_bg_inner;   // Cerchio interno AUTONOMIA - AGGIUNTO
extern lv_obj_t * ui_automark;            // Arco AUTONOMIA

// === ALTRI OGGETTI ===
extern lv_obj_t * ui_socvalue;
extern lv_obj_t * ui_soc;
extern lv_obj_t * ui_automvalue;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_regenbar;
extern lv_obj_t * ui_regenbar_sep1;    // Separatore 1 regenbar
extern lv_obj_t * ui_regenbar_sep2;    // Separatore 2 regenbar
extern lv_obj_t * ui_powerbar;
extern lv_obj_t * ui_powerbar_sep1;    // Separatore 1 powerbar
extern lv_obj_t * ui_powerbar_sep2;    // Separatore 2 powerbar
extern lv_obj_t * ui_messaggi;
extern lv_obj_t * ui_regenvalue;
extern lv_obj_t * ui_powervalue;
extern lv_obj_t * ui_Battery;
extern lv_obj_t * ui_battemp;

// === BOTTONI ===
extern lv_obj_t * ui_sport;
extern lv_obj_t * ui_Labelsport;
extern lv_obj_t * ui_normal;
extern lv_obj_t * ui_Labelnormal;
extern lv_obj_t * ui_ice;
extern lv_obj_t * ui_Labelice;
extern lv_obj_t * ui_reset;
extern lv_obj_t * ui_Labelreset;

// === OGGETTI OMBRE VECCHI (se presenti) ===
extern lv_obj_t * ui_ombraDXArancio;      // Mantieni se presente
extern lv_obj_t * ui_ombraDXRosso;        // Mantieni se presente
extern lv_obj_t * ui_ombraDX;             // Mantieni se presente
extern lv_obj_t * ui_ombraSX;             // Mantieni se presente
extern lv_obj_t * ui_cerchioDX;           // Mantieni se presente
extern lv_obj_t * ui_cerchioSX;           // Mantieni se presente

// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_desi12);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif