// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// === BACKGROUND DA SD IN PSRAM ===
// Dichiarazioni esterne (definite in main.cpp)
extern lv_img_dsc_t background_img_dsc;
extern bool background_loaded;

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // === BACKGROUND DINAMICO DA SD ===
    // Se background.jpg è stato caricato da SD in PSRAM, usalo
    // Altrimenti usa un gradiente scuro come fallback
    if (background_loaded) {
        lv_obj_set_style_bg_img_src(ui_Screen2, &background_img_dsc, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_img_opa(ui_Screen2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    } else {
        // Fallback: gradiente scuro automotive
        lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x1A1A2E), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_grad_color(ui_Screen2, lv_color_hex(0x0F0F1E), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_grad_dir(ui_Screen2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    
    ui_socark2 = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_socark2, 241);
    lv_obj_set_height(ui_socark2, 241);
    lv_obj_set_x(ui_socark2, 0);
    lv_obj_set_y(ui_socark2, -29);
    lv_obj_set_align(ui_socark2, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_socark2, 50);
    lv_obj_set_style_arc_width(ui_socark2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_socark2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_socark2, lv_color_hex(0x4140FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_socark2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_socark2, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_socark2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_socark2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_socark2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_socvalueC = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_socvalueC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_socvalueC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_socvalueC, 0);
    lv_obj_set_y(ui_socvalueC, -19);
    lv_obj_set_align(ui_socvalueC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_socvalueC, "100%");
    lv_obj_set_style_text_align(ui_socvalueC, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_socvalueC, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, -67);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "SOC");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, 79);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Time to end");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, 126);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "1.56");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    // === PANEL MESSAGGI ERRORI Screen2 (bordi tondi, sfondo colorato dinamico) ===
    ui_Panel_messaggiC = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel_messaggiC, 300);
    lv_obj_set_height(ui_Panel_messaggiC, 65);
    lv_obj_set_x(ui_Panel_messaggiC, 0);
    lv_obj_set_y(ui_Panel_messaggiC, 182);
    lv_obj_set_align(ui_Panel_messaggiC, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_messaggiC, LV_OBJ_FLAG_SCROLLABLE);
    // Bordi completamente arrotondati (pillola)
    lv_obj_set_style_radius(ui_Panel_messaggiC, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    // Sfondo verde automotive morbido (Sistema OK) - 0x2D8659
    lv_obj_set_style_bg_color(ui_Panel_messaggiC, lv_color_hex(0x2D8659), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_messaggiC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // Nessun bordo
    lv_obj_set_style_border_width(ui_Panel_messaggiC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // === LABEL MESSAGGI (testo nero sopra il panel colorato) ===
    ui_messaggiC = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_messaggiC, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_messaggiC, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_messaggiC, 0);
    lv_obj_set_y(ui_messaggiC, 182);
    lv_obj_set_align(ui_messaggiC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_messaggiC, "Sistema OK");
    lv_obj_set_style_text_font(ui_messaggiC, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    // Testo sempre NERO
    lv_obj_set_style_text_color(ui_messaggiC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_messaggiC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



}
