// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// === BACKGROUND DA SD IN PSRAM ===
// Dichiarazioni esterne (definite in main.cpp)
extern lv_img_dsc_t background_img_dsc;
extern bool background_loaded;

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // === BACKGROUND DINAMICO DA SD ===
    // Se background.jpg è stato caricato da SD in PSRAM, usalo
    // Altrimenti usa un gradiente scuro come fallback
    if (background_loaded) {
        lv_obj_set_style_bg_img_src(ui_Screen1, &background_img_dsc, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_img_opa(ui_Screen1, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    } else {
        // Fallback: gradiente scuro automotive
        lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x1A1A2E), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_grad_color(ui_Screen1, lv_color_hex(0x0F0F1E), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_grad_dir(ui_Screen1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    
    // === PANEL MESSAGGI ERRORI (bordi tondi, sfondo colorato dinamico) ===
    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 300);
    lv_obj_set_height(ui_Panel3, 45);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 192);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);
    // Bordi completamente arrotondati (pillola)
    lv_obj_set_style_radius(ui_Panel3, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    // Sfondo verde automotive morbido (Sistema OK) - 0x2D8659
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x2D8659), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // Nessun bordo
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gear = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_gear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gear, 0);
    lv_obj_set_y(ui_gear, 24);
    lv_obj_set_align(ui_gear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gear, "Gear");
    lv_obj_set_style_text_color(ui_gear, lv_color_hex(0xA09F9F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gear, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gearvalue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_gearvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gearvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gearvalue, 0);
    lv_obj_set_y(ui_gearvalue, 79);
    lv_obj_set_align(ui_gearvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gearvalue, "R");
    // Colore automotive morbido (grigio chiaro ma non abbagliante) - 0xB8B8B8
    lv_obj_set_style_text_color(ui_gearvalue, lv_color_hex(0xB8B8B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gearvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gearvalue, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedvalue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_speedvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedvalue, 0);
    lv_obj_set_y(ui_speedvalue, -49);
    lv_obj_set_align(ui_speedvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedvalue, "120");
    // Colore automotive morbido per numeri principali - 0xD0D0D0
    lv_obj_set_style_text_color(ui_speedvalue, lv_color_hex(0xD0D0D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedvalue, &ui_font_desi12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_knh = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_knh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_knh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_knh, 139);
    lv_obj_set_y(ui_knh, -80);
    lv_obj_set_align(ui_knh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_knh, "km/h");
    lv_obj_set_style_text_font(ui_knh, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_odo = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_odo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_odo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_odo, -55);
    lv_obj_set_y(ui_odo, 134);
    lv_obj_set_align(ui_odo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_odo, "ODO :");
    lv_obj_set_style_text_font(ui_odo, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_odovalue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_odovalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_odovalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_odovalue, 38);
    lv_obj_set_y(ui_odovalue, 134);
    lv_obj_set_align(ui_odovalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_odovalue, "--");
    lv_obj_set_style_text_font(ui_odovalue, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

// === BLOCCO SOC OTTIMIZZATO CON CERCHI PIENI TRASPARENTI ===

// CERCHIO ESTERNO SOC - Effetto alone (sostituisce l'ombra)
ui_socark_bg = lv_obj_create(ui_Screen1);
lv_obj_set_width(ui_socark_bg, 270);  // Più grande per effetto alone
lv_obj_set_height(ui_socark_bg, 270);
lv_obj_set_x(ui_socark_bg, -240);
lv_obj_set_y(ui_socark_bg, 50);
lv_obj_set_align(ui_socark_bg, LV_ALIGN_CENTER);
lv_obj_clear_flag(ui_socark_bg, LV_OBJ_FLAG_SCROLLABLE);
lv_obj_set_style_radius(ui_socark_bg, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);

// Cerchio pieno BLU trasparente (MOLTO più efficiente delle ombre)
lv_obj_set_style_bg_color(ui_socark_bg, lv_color_hex(0x40A5FF), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_socark_bg, 25, LV_PART_MAIN | LV_STATE_DEFAULT);  // 25% trasparenza
lv_obj_set_style_border_width(ui_socark_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

// CERCHIO INTERNO SOC - Intensità centrale
ui_socark_bg_inner = lv_obj_create(ui_Screen1);
lv_obj_set_width(ui_socark_bg_inner, 210);
lv_obj_set_height(ui_socark_bg_inner, 210);
lv_obj_set_x(ui_socark_bg_inner, -240);
lv_obj_set_y(ui_socark_bg_inner, 50);
lv_obj_set_align(ui_socark_bg_inner, LV_ALIGN_CENTER);
lv_obj_clear_flag(ui_socark_bg_inner, LV_OBJ_FLAG_SCROLLABLE);
lv_obj_set_style_radius(ui_socark_bg_inner, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_socark_bg_inner, lv_color_hex(0x40A5FF), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_socark_bg_inner, 15, LV_PART_MAIN | LV_STATE_DEFAULT);  // 15% trasparenza
lv_obj_set_style_border_width(ui_socark_bg_inner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

// ARCO SOC (sopra i cerchi trasparenti) - UGUALE AL TUO ORIGINALE
ui_socark = lv_arc_create(ui_Screen1);
lv_obj_set_width(ui_socark, 206);
lv_obj_set_height(ui_socark, 206);
lv_obj_set_x(ui_socark, -240);
lv_obj_set_y(ui_socark, 50);
lv_obj_set_align(ui_socark, LV_ALIGN_CENTER);
lv_arc_set_value(ui_socark, 50);
lv_obj_set_style_arc_width(ui_socark, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_socark, false, LV_PART_MAIN | LV_STATE_DEFAULT);

// Stili indicatore SOC - UGUALE AL TUO ORIGINALE
lv_obj_set_style_arc_color(ui_socark, lv_color_hex(0x40A5FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
lv_obj_set_style_arc_opa(ui_socark, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_socark, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_socark, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

// Knob trasparente SOC - UGUALE AL TUO ORIGINALE
lv_obj_set_style_bg_color(ui_socark, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_socark, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

// === BLOCCO AUTONOMIA OTTIMIZZATO CON CERCHI PIENI TRASPARENTI DINAMICI ===

// CERCHIO ESTERNO AUTONOMIA - Effetto alone dinamico (sostituisce l'ombra)
ui_automark_bg = lv_obj_create(ui_Screen1);
lv_obj_set_width(ui_automark_bg, 270);  // Più grande per effetto alone
lv_obj_set_height(ui_automark_bg, 270);
lv_obj_set_x(ui_automark_bg, 240);
lv_obj_set_y(ui_automark_bg, 50);
lv_obj_set_align(ui_automark_bg, LV_ALIGN_CENTER);
lv_obj_clear_flag(ui_automark_bg, LV_OBJ_FLAG_SCROLLABLE);
lv_obj_set_style_radius(ui_automark_bg, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);

// CERCHIO VISIBILE VERDE TRASPARENTE (invece di ombra)
lv_obj_set_style_bg_color(ui_automark_bg, lv_color_hex(0x5CFC66), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_automark_bg, 25, LV_PART_MAIN | LV_STATE_DEFAULT);  // 25% trasparenza - VISIBILE
lv_obj_set_style_border_width(ui_automark_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

// CERCHIO INTERNO AUTONOMIA - Intensità centrale dinamica
ui_automark_bg_inner = lv_obj_create(ui_Screen1);
lv_obj_set_width(ui_automark_bg_inner, 210);
lv_obj_set_height(ui_automark_bg_inner, 210);
lv_obj_set_x(ui_automark_bg_inner, 240);
lv_obj_set_y(ui_automark_bg_inner, 50);
lv_obj_set_align(ui_automark_bg_inner, LV_ALIGN_CENTER);
lv_obj_clear_flag(ui_automark_bg_inner, LV_OBJ_FLAG_SCROLLABLE);
lv_obj_set_style_radius(ui_automark_bg_inner, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_automark_bg_inner, lv_color_hex(0x5CFC66), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_automark_bg_inner, 15, LV_PART_MAIN | LV_STATE_DEFAULT);  // 15% trasparenza
lv_obj_set_style_border_width(ui_automark_bg_inner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

// ARCO AUTONOMIA (sopra i cerchi trasparenti) - UGUALE AL TUO ORIGINALE
ui_automark = lv_arc_create(ui_Screen1);
lv_obj_set_width(ui_automark, 206);
lv_obj_set_height(ui_automark, 206);
lv_obj_set_x(ui_automark, 240);
lv_obj_set_y(ui_automark, 50);
lv_obj_set_align(ui_automark, LV_ALIGN_CENTER);
lv_arc_set_value(ui_automark, 50);
lv_obj_set_style_arc_width(ui_automark, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_automark, false, LV_PART_MAIN | LV_STATE_DEFAULT);

// Stili indicatore AUTONOMIA - UGUALE AL TUO ORIGINALE
lv_obj_set_style_arc_color(ui_automark, lv_color_hex(0x25FC32), LV_PART_INDICATOR | LV_STATE_DEFAULT);
lv_obj_set_style_arc_opa(ui_automark, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_automark, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_automark, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

// Knob trasparente AUTONOMIA - UGUALE AL TUO ORIGINALE
lv_obj_set_style_bg_color(ui_automark, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_automark, 0, LV_PART_KNOB | LV_STATE_DEFAULT);


    ui_socvalue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_socvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_socvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_socvalue, -240);
    lv_obj_set_y(ui_socvalue, 41);
    lv_obj_set_align(ui_socvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_socvalue, "000");
    lv_obj_set_style_text_font(ui_socvalue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_soc = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_soc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_soc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_soc, -240);
    lv_obj_set_y(ui_soc, 128);
    lv_obj_set_align(ui_soc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_soc, "SOC");
    lv_obj_set_style_text_color(ui_soc, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_soc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_soc, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_soc, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_automvalue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_automvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_automvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_automvalue, 240);
    lv_obj_set_y(ui_automvalue, 41);
    lv_obj_set_align(ui_automvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_automvalue, "0");
    lv_obj_set_style_text_font(ui_automvalue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 240);
    lv_obj_set_y(ui_Label6, 128);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "KM");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

     ui_regenbar = lv_bar_create(ui_Screen1);
    lv_bar_set_range(ui_regenbar, 0, 100);
    lv_bar_set_value(ui_regenbar, 0, LV_ANIM_OFF);  // esempio: 30% di rigenerazione
    lv_obj_set_width(ui_regenbar, 280);
    lv_obj_set_height(ui_regenbar, 20);
    lv_obj_set_x(ui_regenbar, -208);  // Posizione simmetrica rispetto alla powerbar
    lv_obj_set_y(ui_regenbar, -173);
    lv_obj_set_align(ui_regenbar, LV_ALIGN_CENTER);

    // Sfondo barra (parte non riempita)
    lv_obj_set_style_bg_color(ui_regenbar, lv_color_hex(0x1B1F23), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_regenbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Indicatore (parte riempita - verde)
    lv_obj_set_style_bg_color(ui_regenbar, lv_color_hex(0x0AAB02), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_regenbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Direzione da destra verso sinistra
    lv_obj_set_style_base_dir(ui_regenbar, LV_BASE_DIR_RTL, 0);
    lv_obj_set_style_bg_color(ui_regenbar, lv_color_hex(0x0AAB02), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_regenbar, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_regenbar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // === SEPARATORI REGENBAR (3 zone: 0-33% | 33-66% | 66-100%) ===
    // La barra è centrata a x=-208, larghezza 280px
    // Inizio barra: -208 - 140 = -348
    // Separatore 1 a 33%: -348 + 93 = -255
    ui_regenbar_sep1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_regenbar_sep1, 4);  // Linea più spessa
    lv_obj_set_height(ui_regenbar_sep1, 20);
    lv_obj_set_x(ui_regenbar_sep1, -255);  // Posizione a 1/3 della barra
    lv_obj_set_y(ui_regenbar_sep1, -173);
    lv_obj_set_align(ui_regenbar_sep1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_regenbar_sep1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_regenbar_sep1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_regenbar_sep1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Separatore 2 a 66%: -348 + 186 = -162
    ui_regenbar_sep2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_regenbar_sep2, 4);  // Linea più spessa
    lv_obj_set_height(ui_regenbar_sep2, 20);
    lv_obj_set_x(ui_regenbar_sep2, -162);  // Posizione a 2/3 della barra
    lv_obj_set_y(ui_regenbar_sep2, -173);
    lv_obj_set_align(ui_regenbar_sep2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_regenbar_sep2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_regenbar_sep2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_regenbar_sep2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_powerbar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_powerbar, 0, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_powerbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_powerbar, 280);
    lv_obj_set_height(ui_powerbar, 20);
    lv_obj_set_x(ui_powerbar, 208);
    lv_obj_set_y(ui_powerbar, -173);
    lv_obj_set_align(ui_powerbar, LV_ALIGN_CENTER);

    // Sfondo barra (parte non riempita)
    lv_obj_set_style_bg_color(ui_powerbar, lv_color_hex(0x1B1F23), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powerbar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // === Parte indicator con gradiente ===
    lv_obj_set_style_bg_color(ui_powerbar, lv_color_hex(0xFFA500), LV_PART_INDICATOR | LV_STATE_DEFAULT);  // Arancione iniziale
    lv_obj_set_style_bg_grad_color(ui_powerbar, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);  // Rosso finale
    lv_obj_set_style_bg_grad_dir(ui_powerbar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);  // Gradiente orizzontale
    lv_obj_set_style_bg_opa(ui_powerbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // === SEPARATORI POWERBAR (3 zone: 0-33% | 33-66% | 66-100%) ===
    // La barra è centrata a x=208, larghezza 280px
    // Inizio barra: 208 - 140 = 68
    // Separatore 1 a 33%: 68 + 93 = 161
    ui_powerbar_sep1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_powerbar_sep1, 4);  // Linea più spessa
    lv_obj_set_height(ui_powerbar_sep1, 20);
    lv_obj_set_x(ui_powerbar_sep1, 161);  // Posizione a 1/3 della barra
    lv_obj_set_y(ui_powerbar_sep1, -173);
    lv_obj_set_align(ui_powerbar_sep1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_powerbar_sep1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powerbar_sep1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_powerbar_sep1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Separatore 2 a 66%: 68 + 186 = 254
    ui_powerbar_sep2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_powerbar_sep2, 4);  // Linea più spessa
    lv_obj_set_height(ui_powerbar_sep2, 20);
    lv_obj_set_x(ui_powerbar_sep2, 254);  // Posizione a 2/3 della barra
    lv_obj_set_y(ui_powerbar_sep2, -173);
    lv_obj_set_align(ui_powerbar_sep2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_powerbar_sep2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powerbar_sep2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_powerbar_sep2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    // === LABEL MESSAGGI (testo nero sopra il panel colorato) ===
    ui_messaggi = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_messaggi, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_messaggi, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_messaggi, -1);
    lv_obj_set_y(ui_messaggi, 190);
    lv_obj_set_align(ui_messaggi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_messaggi, "Sistema OK");
    // Font più grande per maggior leggibilità automotive
    lv_obj_set_style_text_font(ui_messaggi, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    // Testo sempre NERO
    lv_obj_set_style_text_color(ui_messaggi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_messaggi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_regenvalue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_regenvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_regenvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_regenvalue, -107);
    lv_obj_set_y(ui_regenvalue, -146);
    lv_obj_set_align(ui_regenvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_regenvalue, "0kw");
    lv_obj_set_style_text_font(ui_regenvalue, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_powervalue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_powervalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powervalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_powervalue, 95);
    lv_obj_set_y(ui_powervalue, -146);
    lv_obj_set_align(ui_powervalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_powervalue, "0kw");
    lv_obj_set_style_text_font(ui_powervalue, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Battery = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Battery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Battery, -55);
    lv_obj_set_y(ui_Battery, -202);
    lv_obj_set_align(ui_Battery, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Battery, "Battery");
    lv_obj_set_style_text_font(ui_Battery, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_battemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_battemp, 40);
    lv_obj_set_y(ui_battemp, -202);
    lv_obj_set_align(ui_battemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_battemp, "27°");
    lv_obj_set_style_text_font(ui_battemp, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sport = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_sport, 100);
    lv_obj_set_height(ui_sport, 50);
    lv_obj_set_x(ui_sport, -3);
    lv_obj_set_y(ui_sport, 192);
    lv_obj_set_align(ui_sport, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sport, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_sport, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sport, lv_color_hex(0xCC0606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sport, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelsport = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Labelsport, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelsport, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelsport, -3);
    lv_obj_set_y(ui_Labelsport, 190);
    lv_obj_set_align(ui_Labelsport, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelsport, "Sport");
    lv_obj_add_flag(ui_Labelsport, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_Labelsport, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_normal = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_normal, 100);
    lv_obj_set_height(ui_normal, 50);
    lv_obj_set_x(ui_normal, -3);
    lv_obj_set_y(ui_normal, 192);
    lv_obj_set_align(ui_normal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_normal, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_normal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_normal, lv_color_hex(0x069D0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_normal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelnormal = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Labelnormal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelnormal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelnormal, -3);
    lv_obj_set_y(ui_Labelnormal, 190);
    lv_obj_set_align(ui_Labelnormal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelnormal, "Norm");
    lv_obj_add_flag(ui_Labelnormal, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_Labelnormal, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ice = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ice, 100);
    lv_obj_set_height(ui_ice, 50);
    lv_obj_set_x(ui_ice, -3);
    lv_obj_set_y(ui_ice, 192);
    lv_obj_set_align(ui_ice, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ice, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ice, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ice, lv_color_hex(0x068E9D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ice, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelice = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Labelice, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelice, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelice, -3);
    lv_obj_set_y(ui_Labelice, 190);
    lv_obj_set_align(ui_Labelice, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelice, "Ice");
    lv_obj_add_flag(ui_Labelice, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_Labelice, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_reset = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_reset, 100);
    lv_obj_set_height(ui_reset, 50);
    lv_obj_set_x(ui_reset, -3);
    lv_obj_set_y(ui_reset, 192);
    lv_obj_set_align(ui_reset, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_reset, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_reset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_reset, lv_color_hex(0xF6C328), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_reset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelreset = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Labelreset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelreset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelreset, -3);
    lv_obj_set_y(ui_Labelreset, 190);
    lv_obj_set_align(ui_Labelreset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelreset, "reset");
    lv_obj_add_flag(ui_Labelreset, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Labelreset, lv_color_hex(0xE40C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelreset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelreset, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

}
